### ISSUE TITLE
Verify read-only static keys are actually read-only

### ISSUE THREAD

**Issue by kees** [KSPP/linux#107]
The _RO type of static keys are supposed to be read-only-after-init, but some testing appears to indicate that they are not behavior the way I'd expected. (i.e. calling their enable() functions, for example, still enable when it should be read-only disabled.) This needs further examination.

**Comment by ihalip** [comment]
I modified the existing test_static_keys selftest to create a few read-only keys, and apparently they work as expected: they can be modified during __init, but attempting to modify them after that triggers a page fault. See [this commit](https://github.com/ihalip/linux/commit/21bcbbf8ce9cead8f228c53877600f93111e014a).

```
root@ubuntu-focal:~# cat /sys/kernel/static_keys_ro/ro_keys 
base_true_ro=1, base_false_ro=0, base_inv_true_ro=0, base_inv_false_ro=1
root@ubuntu-focal:~# echo "1 0 0 1" > /sys/kernel/static_keys_ro/ro_keys 
root@ubuntu-focal:~# echo "0 0 0 1" > /sys/kernel/static_keys_ro/ro_keys 
Killed
vagrant@ubuntu-focal:~$ dmesg 
[  100.595391] setting true_ro=1, false_ro=0, inv_true_ro=0, inv_false_ro=1
[  104.872658] setting true_ro=0, false_ro=0, inv_true_ro=0, inv_false_ro=1
[  104.872677] BUG: unable to handle page fault for address: ffffffffc0848030
[  104.873791] #PF: supervisor write access in kernel mode
[  104.874529] #PF: error_code(0x0003) - permissions violation
```

**Comment by kees** [comment]
Nice! Thanks for testing this. Either the prior testing was incorrect or this has been fixed at some point along the way. I'll close this bug. :)
