### ISSUE TITLE
Replace UAPI one-element arrays with flexible-array members

### ISSUE THREAD

**Issue by GustavoARSilva** [KSPP/linux#113]
There are currently 7 files containing one-element arrays in UAPI:

- [x] include/uapi/linux/in.h commit 5854a09b49574da5a77a0f36ad7b021a2661321d
- [x] include/uapi/xen/gntalloc.h https://lore.kernel.org/lkml/20240206170320.work.437-kees@kernel.org
- [x] false positive  include/uapi/linux/netfilter/nf_nat.h
- [x] false positive include/uapi/linux/videodev2.h
- [x] false positive  include/uapi/linux/coff.h
- [x] include/uapi/linux/isst_if.h
  - these are not actually being addressed by the kernel
- [x] include/uapi/scsi/fc/fc_els.h commit 94dfc73e7cf4a31da66b8843f0b9283ddd6b8381

**Comment by GustavoARSilva** [comment]
The following patches are currently being tested:

https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=testing/uapi/gntalloc&id=c3e1cfe0e4ca509f86dfd46bdcf1e41cb76194eb 
https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=testing/uapi/ipv4&id=fcf5365d0c33dedef4d17e545bfa45099ec6c8b7

**Comment by GustavoARSilva** [comment]
Apparently, the one-element arrays in include/uapi/linux/videodev2.h are merely placeholders for alignment, and are not being used as variable-length arrays.

**Comment by GustavoARSilva** [comment]
The following patches are currently being tested:

include/uapi/xen/gntalloc.h
[patch] https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=testing/uapi/gntalloc&id=c3e1cfe0e4ca509f86dfd46bdcf1e41cb76194eb 
[build-test] https://lore.kernel.org/lkml/5f97ff5e.j2HxnldWOU8wavXB%25lkp@intel.com/

include/uapi/linux/in.h
[patch] https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=testing/uapi/ipv4&id=fcf5365d0c33dedef4d17e545bfa45099ec6c8b7
[build-test] https://lore.kernel.org/lkml/5f99ac66.iufpyv3IjodJo6da%25lkp@intel.com/

include/uapi/linux/in.h
[patch] https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=testing/uapi/fam1/ipv4_6&id=a841122b213f5a2106a9321e905da233c8a86390
[build-test] https://lore.kernel.org/lkml/5f9ac6cf.aWpjHOXOIbcQf8Xa%25lkp@intel.com/

include/uapi/linux/netfilter/nf_nat.h
[patch] https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=testing/uapi/netfilter&id=91b7283a05efa53a50234852de97827317e4f98b
[build-test]

**Comment by kees** [comment]
It's non-trivial to update UAPI headers, so to eliminate one-element arrays, it's likely that anonymous unions need to be used. There are some caveats with that, though:

https://www.mail-archive.com/ovs-dev@openvswitch.org/msg48095.html

**Comment by kees** [comment]
All the UAPI 1-element arrays used as flexible arrays have been refactored.
