### ISSUE TITLE
Enable -Wimplicit-fallthrough for Clang

### ISSUE THREAD

**Issue by GustavoARSilva** [KSPP/linux#115]
Fix all fall-through warnings in order to enable -Wimplicit-fallthrough for Clang.

In preparation to enable -Wimplicit-fallthrough for Clang, explicitly
add multiple break/goto/return/fallthrough statements instead of letting
the code fall through to the next case.

Notice that in order to enable -Wimplicit-fallthrough for Clang, this change[1]
is meant to be reverted at some point.

Something important to mention is that there is currently a discrepancy
between GCC and Clang when dealing with switch fall-through to empty case
statements or to cases that only contain a break/continue/return
statement[2][3][4].

Now that the -Wimplicit-fallthrough option has been globally enabled[5],
any compiler should really warn on missing either a fallthrough annotation
or any of the other case-terminating statements (break/continue/return/
goto) when falling through to the next case statement. Making exceptions
to this introduces variation in case handling which may continue to lead
to bugs, misunderstandings, and a general lack of robustness. The point
of enabling options like -Wimplicit-fallthrough is to prevent human error
and aid developers in spotting bugs before their code is even built/
submitted/committed, therefore eliminating classes of bugs. So, in order
to really accomplish this, we should, and can, move in the direction of
addressing any error-prone scenarios and get rid of the unintentional
fallthrough bug-class in the kernel, entirely, even if there is some minor
redundancy. Better to have explicit case-ending statements than continue to
have exceptions where one must guess as to the right result. The compiler
will eliminate any actual redundancy.

[1] commit e2079e93f562c ("kbuild: Do not enable -Wimplicit-fallthrough for clang for now")
[2] https://github.com/ClangBuiltLinux/linux/issues/636
[3] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91432
[4] https://godbolt.org/z/xgkvIh
[5] commit a035d552a93b ("Makefile: Globally enable fall-through warning")

The following patch (already in mainline 5.10-rc2 :) ) addresses almost **40,000 fall-through warnings**:

[include: jhash/signal: Fix fall-through warnings for Clang](https://git.kernel.org/linus/4169e889e5889405d54cec27d6e9f7f0ce3c7096)

```
linux$ git branch --show-current
linux-5.10-rc1
linux$ git log --oneline | head -2
0d3f38450734 Revert "kbuild: Do not enable -Wimplicit-fallthrough for clang for now"
3650b228f83a Linux 5.10-rc1
linux$ grep 'warning: unannotated fall-through' clang-ft-linux-5.10-rc1-allmodconfig.log | wc -l
39608
linux$
linux$ git checkout linux-5.10-rc2
Switched to branch 'linux-5.10-rc2'
linux$ git log --oneline | head -2
f792d8357774 Revert "kbuild: Do not enable -Wimplicit-fallthrough for clang for now"
3cea11cd5e3b Linux 5.10-rc2
linux$ grep 'warning: unannotated fall-through' clang-ft-linux-5.10-rc2-allmodconfig.log | wc -l
442
```

There are currently **440 of these warnings remaining** in next-20201102:

```
linux$ git log --oneline | head -2
d7e66b50d324 Revert "kbuild: Do not enable -Wimplicit-fallthrough for clang for now"
b49976d8ef64 Add linux-next specific files for 20201102
linux$ grep 'warning: unannotated fall-through' clang-testing-next-20201102.log | wc -l
440
```

**Comment by GustavoARSilva** [comment]
This patch is waiting for some test results from 0-day: https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=testing/clang/fallthrough

After applying the patch above to next-20201112, we have **134 warnings left**:

```
linux$ git log --oneline | head -2
a591d72e02d4 Revert "kbuild: Do not enable -Wimplicit-fallthrough for clang for now"
a60b1e1fe9ca Add linux-next specific files for 20201112
linux$ grep 'warning: unannotated fall-through' clang-testing-next-20201112.log | wc -l
134
```

**Comment by GustavoARSilva** [comment]
@kees
This branch was created on top of next-20210422 and contains all the fall-through patches that are waiting to be taken and applied by the maintainers:

https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/log/?h=testing/clang/Wimplicit-fallthrough

The following 17 warnings remain to be addressed:

arch/x86/kvm/cpuid.c:637:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
arch/x86/kvm/vmx/vmx.c:6266:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
kernel/debug/debug_core.c:1041:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
kernel/trace/ring_buffer.c:3395:3: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
sound/soc/ti/davinci-mcasp.c:2320:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/input/joystick/sidewinder.c:663:5: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/scsi/aic94xx/aic94xx_sds.c:722:3: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/net/ethernet/marvell/octeontx2/nic/otx2_flows.c:554:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
fs/xfs/xfs_log.c:2627:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/scsi/mpt3sas/mpt3sas_base.c:4437:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/scsi/mpt3sas/mpt3sas_scsih.c:11935:3: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/staging/rtl8188eu/core/rtw_mlme_ext.c:3384:3: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/net/ethernet/realtek/r8169_main.c:4120:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
fs/xfs/scrub/agheader.c:89:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/staging/rtl8188eu/core/rtw_wlan_util.c:1032:4: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/staging/rtl8188eu/core/rtw_wlan_util.c:1230:3: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
drivers/net/ethernet/xilinx/xilinx_axienet_main.c:1546:2: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]

**Comment by GustavoARSilva** [comment]
Added ignored patches to my -next branch for v5.14:

https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/log/?h=for-next/kspp

**Comment by GustavoARSilva** [comment]
Done: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e9338abf0e186336022293d2e454c106761f262b :)

**Comment by GustavoARSilva** [comment]
The patch for Makefile was reverted by Linus: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d936eb23874433caa3e3d841cfa16f5434b85dcf

**Comment by kees** [comment]
> The patch for Makefile was reverted by Linus: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d936eb23874433caa3e3d841cfa16f5434b85dcf

Clang bug: https://github.com/ClangBuiltLinux/linux/issues/1429

**Comment by GustavoARSilva** [comment]
Closing this issue now:

https://git.kernel.org/linus/dee2b702bcf067d7b6b62c18bdd060ff0810a800
