### ISSUE TITLE
Replace one-element arrays with flexible-array members in UAPI

### ISSUE THREAD

**Issue by kees** [KSPP/linux#120]
It's non-trivial to update UAPI headers, so to eliminate one-element arrays, it's likely that anonymous unions need to be used. There are some caveats with that, though:

https://www.mail-archive.com/ovs-dev@openvswitch.org/msg48095.html

**Comment by GustavoARSilva** [comment]
There is already an issue for this:
https://github.com/KSPP/linux/issues/113

**Comment by kees** [comment]
Ah, thank you! :) I missed it.
