### ISSUE TITLE
Prevent kprobes from “leaking” symbol addresses

### ISSUE THREAD

**Issue by skitt** [KSPP/linux#131]
Even though `kallsyms_lookup_name` is no longer exported, modules can still find it by registering a kprobe for it, thus yielding its address, and then calling it. I’m wondering if it would be possible to avoid revealing `addr` when a kprobe is registered using a symbol name; the kprobe framework itself needs the address obviously, but AFAICT none of the in-kernel kprobe users, apart from the kprobe example, actually uses the address.

**Comment by skitt** [comment]
My thoughts on this are that `addr` in `struct kprobe` could be changed to an opaque value, with no way for modules to decode it. For example (probably not perfect), `kprobes.c` could initialise a randomly-chosen value at boot, and the address in `struct kprobe` would be XORed with it — given the structure of valid kprobe pointers, this could even guarantee that the encoded address is invalid when used as a pointer, at least on x86 (0x80...).

The transition would go something like this:
* change `kprobe_opcode_t *addr` in `struct kprobe` to `unsigned long encaddr` (so that missed users cause compilation errors)
* wherever `addr` is read, use a decoder macro, unless it’s a presence check or a copy
* wherever `addr` is written, use an encoder macro, unless it’s a copy

At first glance this doesn’t add too much processing to hot paths. Since the macros would need access to the obscuring value in `kprobes.c`, modules wouldn’t be able to use them, and thus wouldn’t be able to decode the stored addresses.

(It’s worth noting here that the encoding should strive to ensure that the encoded pointer is never 0 for valid pointer values, so that we can keep cheap presence checks. Knowing that a pointer is null doesn’t leak useful information AFAICT.)

**Comment by kees** [comment]
I think the threat model for kallsyms_lookup_name() is "legitimate kernel modules", for which the unexport was sufficient. A kernel module that wishes to intentionally bypass these things is going to find a way. I'm not sure it's useful complicating kprobes here? Maybe there's something I'm not seeing about this?

**Comment by skitt** [comment]
Right, there’s no security threat AFAICT — if an attacker can cause a kernel module to be loaded, the game’s largely over anyway, and if they control the kernel module, it’s definitely over. I was curious about reducing the exposure of symbols, following the removal of the `kallsyms_lookup_name` export. But it does seem overkill.
