### ISSUE TITLE
Enable -Wcast-function-type globally

### ISSUE THREAD

**Issue by kees** [KSPP/linux#20]
In order to make sure new function cast mismatches are not introduced in the kernel (to avoid tripping CFI checking), the kernel should be globally built with -Wcast-function-type. Many call sites need to be fixed before this can happen.

**Comment by kees** [comment]
Excluding the fixes being developed for crypto, bnx2x, and staging/rtl*, the remaining 23 cases found with an x86_65 allmodconfig build are:

```
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘unsigned int (*)(const void *, const struct bpf_insn *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘void * (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *, void *, u64)’ {aka ‘int (* const)(struct bpf_map *, void *, void *, long long unsigned int)’} to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *, u64)’ {aka ‘int (* const)(struct bpf_map *, void *, long long unsigned int)’} to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘void * (*)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘void * (*)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
./include/linux/filter.h:344:4: warning: cast between incompatible function types from ‘void * (*)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Wcast-function-type]
drivers/firewire/core-cdev.c:985:8: warning: cast between incompatible function types from ‘void (*)(struct fw_iso_context *, dma_addr_t,  void *)’ {aka ‘void (*)(struct fw_iso_context *, long long unsigned int,  void *)’} to ‘void (*)(struct fw_iso_context *, u32,  size_t,  void *, void *)’ {aka ‘void (*)(struct fw_iso_context *, unsigned int,  long unsigned int,  void *, void *)’} [-Wcast-function-type]
kernel/trace/fgraph.c:337:4: warning: cast between incompatible function types from ‘void (*)(long unsigned int,  long unsigned int,  struct ftrace_ops *, struct pt_regs *)’ to ‘void (*)(struct ftrace_graph_ret *)’ [-Wcast-function-type]
kernel/trace/fgraph.c:617:24: warning: cast between incompatible function types from ‘void (*)(long unsigned int,  long unsigned int,  struct ftrace_ops *, struct pt_regs *)’ to ‘void (*)(struct ftrace_graph_ret *)’ [-Wcast-function-type]
drivers/net/usb/hso.c:1268:9: warning: cast between incompatible function types from ‘void (*)(struct hso_serial *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
drivers/net/wireless/broadcom/b43legacy/main.c:3744:8: warning: cast between incompatible function types from ‘void (*)(struct b43legacy_wldev *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
drivers/net/wireless/intel/ipw2x00/ipw2100.c:6140:35: warning: cast between incompatible function types from ‘void (*)(struct ipw2100_priv *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
drivers/net/wireless/intel/ipw2x00/ipw2200.c:10683:35: warning: cast between incompatible function types from ‘void (*)(struct ipw_priv *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
drivers/net/wireless/intel/iwlegacy/4965-mac.c:6240:8: warning: cast between incompatible function types from ‘void (*)(struct il_priv *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
drivers/net/usb/usbnet.c:1703:17: warning: cast between incompatible function types from ‘void (*)(struct timer_list *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
drivers/net/wireless/intel/iwlegacy/3945-mac.c:3404:8: warning: cast between incompatible function types from ‘void (*)(struct il_priv *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
drivers/net/wireless/realtek/rtlwifi/pci.c:1196:8: warning: cast between incompatible function types from ‘void (*)(struct ieee80211_hw *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
drivers/net/wireless/realtek/rtlwifi/pci.c:1199:8: warning: cast between incompatible function types from ‘void (*)(struct ieee80211_hw *)’ to ‘void (*)(long unsigned int)’ [-Wcast-function-type]
drivers/scsi/aacraid/aachba.c:813:23: warning: cast between incompatible function types from ‘int (*)(struct scsi_cmnd *)’ to ‘void (*)(struct scsi_cmnd *)’ [-Wcast-function-type]

```

**Comment by Blacksuan19** [comment]
patch has been merged, can you close this?

**Comment by kees** [comment]
It's hasn't though. The kernel is still not built with -Wcast-function-type. There are many more cases to fix before that can happen.

**Comment by kees** [comment]
The last two instances appear to be fixed with:

- [ ] https://lore.kernel.org/lkml/20200530090839.7895-1-oscar.carter@gmx.com/
- [ ] https://lore.kernel.org/lkml/20210927182700.2980499-1-keescook@chromium.org/

**Comment by GustavoARSilva** [comment]
> The last two instances appear to be fixed with:
> 
>     * [ ]  https://lore.kernel.org/lkml/20200530090839.7895-1-oscar.carter@gmx.com/
> 
>     * [ ]  https://lore.kernel.org/lkml/20210927182700.2980499-1-keescook@chromium.org/

12 instances, actually:

                 from kernel/bpf/verifier.c:12:
kernel/bpf/verifier.c: In function ‘jit_subprogs’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘unsigned int (*)(const void *, const struct bpf_insn *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12472:16: note: in expansion of macro ‘BPF_CAST_CALL’
--
  CC      kernel/bpf/inode.o
kernel/bpf/verifier.c: In function ‘do_misc_fixups’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘void * (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12953:17: note: in expansion of macro ‘BPF_CAST_CALL’
12953 |     insn->imm = BPF_CAST_CALL(ops->map_lookup_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *, void *, u64)’ {aka ‘int (* const)(struct bpf_map *, void *, void *, long long unsigned int)’} to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12957:17: note: in expansion of macro ‘BPF_CAST_CALL’
12957 |     insn->imm = BPF_CAST_CALL(ops->map_update_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12961:17: note: in expansion of macro ‘BPF_CAST_CALL’
12961 |     insn->imm = BPF_CAST_CALL(ops->map_delete_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *, u64)’ {aka ‘int (* const)(struct bpf_map *, void *, long long unsigned int)’} to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12965:17: note: in expansion of macro ‘BPF_CAST_CALL’
12965 |     insn->imm = BPF_CAST_CALL(ops->map_push_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12969:17: note: in expansion of macro ‘BPF_CAST_CALL’
12969 |     insn->imm = BPF_CAST_CALL(ops->map_pop_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12973:17: note: in expansion of macro ‘BPF_CAST_CALL’
12973 |     insn->imm = BPF_CAST_CALL(ops->map_peek_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, u32,  u64)’ {aka ‘int (* const)(struct bpf_map *, unsigned int,  long long unsigned int)’} to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12977:17: note: in expansion of macro ‘BPF_CAST_CALL’
--
In file included from kernel/bpf/hashtab.c:8:
kernel/bpf/hashtab.c: In function ‘htab_map_gen_lookup’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘void * (*)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
./include/linux/filter.h:374:14: note: in definition of macro ‘BPF_EMIT_CALL’
--
      |                          ^~~~~~~~~~~~~
kernel/bpf/hashtab.c: In function ‘htab_lru_map_gen_lookup’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘void * (*)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
./include/linux/filter.h:374:14: note: in definition of macro ‘BPF_EMIT_CALL’
--
  CC      drivers/char/ipmi/ipmi_kcs_sm.o
kernel/bpf/hashtab.c: In function ‘htab_of_map_gen_lookup’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘void * (*)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
./include/linux/filter.h:374:14: note: in definition of macro ‘BPF_EMIT_CALL’
--
  CC      lib/debug_locks.o
drivers/firewire/core-cdev.c: In function ‘ioctl_create_iso_context’:
drivers/firewire/core-cdev.c:985:8: error: cast between incompatible function types from ‘void (*)(struct fw_iso_context *, dma_addr_t,  void *)’ {aka ‘void (*)(struct fw_iso_context *, long long unsigned int,  void *)’} to ‘void (*)(struct fw_iso_context *, u32,  size_t,  void *, void *)’ {aka ‘void (*)(struct fw_iso_context *, unsigned int,  long unsigned int,  void *, void *)’} [-Werror=cast-function-type]
  985 |   cb = (fw_iso_callback_t)iso_mc_callback;
      |        ^

**Comment by GustavoARSilva** [comment]
> The last two instances appear to be fixed with:
> 
>     * [ ]  https://lore.kernel.org/lkml/20200530090839.7895-1-oscar.carter@gmx.com/
> 
>     * [ ]  https://lore.kernel.org/lkml/20210927182700.2980499-1-keescook@chromium.org/

12 instances, actually:

```
                 from kernel/bpf/verifier.c:12:
kernel/bpf/verifier.c: In function ‘jit_subprogs’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘unsigned int (*)(const void *, const struct bpf_insn *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12472:16: note: in expansion of macro ‘BPF_CAST_CALL’
--
  CC      kernel/bpf/inode.o
kernel/bpf/verifier.c: In function ‘do_misc_fixups’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘void * (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12953:17: note: in expansion of macro ‘BPF_CAST_CALL’
12953 |     insn->imm = BPF_CAST_CALL(ops->map_lookup_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *, void *, u64)’ {aka ‘int (* const)(struct bpf_map *, void *, void *, long long unsigned int)’} to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12957:17: note: in expansion of macro ‘BPF_CAST_CALL’
12957 |     insn->imm = BPF_CAST_CALL(ops->map_update_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12961:17: note: in expansion of macro ‘BPF_CAST_CALL’
12961 |     insn->imm = BPF_CAST_CALL(ops->map_delete_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *, u64)’ {aka ‘int (* const)(struct bpf_map *, void *, long long unsigned int)’} to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12965:17: note: in expansion of macro ‘BPF_CAST_CALL’
12965 |     insn->imm = BPF_CAST_CALL(ops->map_push_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12969:17: note: in expansion of macro ‘BPF_CAST_CALL’
12969 |     insn->imm = BPF_CAST_CALL(ops->map_pop_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12973:17: note: in expansion of macro ‘BPF_CAST_CALL’
12973 |     insn->imm = BPF_CAST_CALL(ops->map_peek_elem) -
      |                 ^~~~~~~~~~~~~
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘int (* const)(struct bpf_map *, u32,  u64)’ {aka ‘int (* const)(struct bpf_map *, unsigned int,  long long unsigned int)’} to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
kernel/bpf/verifier.c:12977:17: note: in expansion of macro ‘BPF_CAST_CALL’
--
In file included from kernel/bpf/hashtab.c:8:
kernel/bpf/hashtab.c: In function ‘htab_map_gen_lookup’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘void * (*)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
./include/linux/filter.h:374:14: note: in definition of macro ‘BPF_EMIT_CALL’
--
      |                          ^~~~~~~~~~~~~
kernel/bpf/hashtab.c: In function ‘htab_lru_map_gen_lookup’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘void * (*)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
./include/linux/filter.h:374:14: note: in definition of macro ‘BPF_EMIT_CALL’
--
  CC      drivers/char/ipmi/ipmi_kcs_sm.o
kernel/bpf/hashtab.c: In function ‘htab_of_map_gen_lookup’:
./include/linux/filter.h:366:4: error: cast between incompatible function types from ‘void * (*)(struct bpf_map *, void *)’ to ‘u64 (*)(u64,  u64,  u64,  u64,  u64)’ {aka ‘long long unsigned int (*)(long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int,  long long unsigned int)’} [-Werror=cast-function-type]
  366 |   ((u64 (*)(u64, u64, u64, u64, u64))(x))
      |    ^
./include/linux/filter.h:374:14: note: in definition of macro ‘BPF_EMIT_CALL’
--
  CC      lib/debug_locks.o
drivers/firewire/core-cdev.c: In function ‘ioctl_create_iso_context’:
drivers/firewire/core-cdev.c:985:8: error: cast between incompatible function types from ‘void (*)(struct fw_iso_context *, dma_addr_t,  void *)’ {aka ‘void (*)(struct fw_iso_context *, long long unsigned int,  void *)’} to ‘void (*)(struct fw_iso_context *, u32,  size_t,  void *, void *)’ {aka ‘void (*)(struct fw_iso_context *, unsigned int,  long unsigned int,  void *, void *)’} [-Werror=cast-function-type]
  985 |   cb = (fw_iso_callback_t)iso_mc_callback;
      |        ^

```

**Comment by kees** [comment]
> 12 instances, actually:

Right, I will adjust the comment. "The remaining warning instances are fixed by these patches"

**Comment by GustavoARSilva** [comment]
These last fixes are now in linux-next:
https://lore.kernel.org/linux-hardening/CAADnVQL7eY1Vs5S+DuYhFKYoP83Vr5CQ5sjn=UT_6Xo3=HGMvw@mail.gmail.com/
https://lore.kernel.org/lkml/20200530090839.7895-1-oscar.carter@gmx.com/

I've just enabled the compiler option in my -next tree:
https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=for-next/cast-function&id=ffea83dd8823401f3922276d36aca35c3e99d7f3

and I'll send a PR for 5.16-rc1.

**Comment by GustavoARSilva** [comment]
Steven is aware of the last warnings on powerpc64 and he's already taking a look:
https://lore.kernel.org/lkml/20211005125132.4ae5d128@gandalf.local.home/
