### ISSUE TITLE
Eliminate fake flexible arrays from the kernel ("variable length" one-element and zero-length arrays)

### ISSUE THREAD

**Issue by kees** [KSPP/linux#21]
Dependent bugs:
- [x] https://github.com/KSPP/linux/issues/78
- [x] https://github.com/KSPP/linux/issues/79
- [x] https://github.com/KSPP/linux/issues/80
- [x] https://github.com/KSPP/linux/issues/113
- [x] https://github.com/KSPP/linux/issues/86
- [x] https://github.com/KSPP/linux/issues/76
- [x] https://github.com/KSPP/linux/issues/137
- [x] [Replace fake FAMs in ACPICA upstream](https://github.com/acpica/acpica/pull/856)
- [x] Compilers must not treat all training arrays as flex arrays (need `-fstrict-flex-arrays=3`)
  - [x] GCC [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101836)
  - [x] Clang [bug](https://github.com/llvm/llvm-project/issues/55741)

There is a regular need in the kernel to provide a way to declare having a
dynamically sized set of trailing elements in a structure. Kernel code should
always use [“flexible array members”](https://en.wikipedia.org/wiki/Flexible_array_member) for these cases. The older style of
one-element or zero-length arrays should no longer be used.

In older C code, dynamically sized trailing elements were done by specifying
a one-element array at the end of a structure:

```
struct something {
        size_t count;
        struct foo items[1];
};
```

This led to fragile size calculations via sizeof() (which would need to remove
the size of the single trailing element to get a correct size of the “header”).
A [GNU C extension](https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html) was introduced to allow for zero-length arrays, to avoid
these kinds of size problems:

```
struct something {
        size_t count;
        struct foo items[0];
};
```
But this led to other problems, and didn’t solve some problems shared by both
styles, like not being able to detect when such an array is accidentally being
used _not_ at the end of a structure (which could happen directly, or when
such a struct was in unions, structs of structs, etc).

C99 introduced “flexible array members”, which lacks a numeric size for the
array declaration entirely:

```
struct something {
        size_t count;
        struct foo items[];
};
```

This is the way the kernel expects dynamically sized trailing elements to be
declared. It allows the compiler to generate errors when the flexible array
does not occur last in the structure, which helps to prevent some kind of
[undefined behavior](https://git.kernel.org/linus/76497732932f15e7323dc805e8ea8dc11bb587cf) bugs from being inadvertently introduced to the codebase.
It also allows the compiler to correctly analyze array sizes (via sizeof(),
CONFIG_FORTIFY_SOURCE, and CONFIG_UBSAN_BOUNDS). For instance, there is no
mechanism that warns us that the following application of the sizeof() operator
to a zero-length array always results in zero:

```
struct something {
        size_t count;
        struct foo items[0];
};

struct something *instance;

instance = kmalloc(struct_size(instance, items, count), GFP_KERNEL);
instance->count = count;

size = sizeof(instance->items) * instance->count;
memcpy(instance->items, source, size);
```

At the last line of code above, size turns out to be zero, when one might have
thought it represents the total size in bytes of the dynamic memory recently
allocated for the trailing array items. Here are a couple examples of this
issue: [link 1](https://git.kernel.org/linus/f2cd32a443da694ac4e28fbf4ac6f9d5cc63a539), [link 2](https://git.kernel.org/linus/ab91c2a89f86be2898cee208d492816ec238b2cf). Instead, [flexible array members have incomplete type, and so the
sizeof() operator may not be applied](https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html), so any misuse of such operators will
be immediately noticed at build time.

With respect to one-element arrays, one has to be acutely aware that [such
arrays occupy at least as much space as a single object of the type, hence they
contribute to the size of the enclosing structure](https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html). This is prone to error every
time people want to calculate the total size of dynamic memory to allocate for
a structure containing an array of this kind as a member:

```
struct something {
        size_t count;
        struct foo items[1];
};

struct something *instance;

instance = kmalloc(struct_size(instance, items, count - 1), GFP_KERNEL);
instance->count = count;

size = sizeof(instance->items) * instance->count;
memcpy(instance->items, source, size);
```

In the example above, we had to remember to calculate count - 1 when using the
struct_size() helper, otherwise we would have –unintentionally– allocated memory
for one too many items objects. The cleanest and least error-prone way to
implement this is through the use of a flexible array member, instead:

```
struct something {
        size_t count;
        struct foo items[];
};

struct something *instance;

instance = kmalloc(struct_size(instance, items, count), GFP_KERNEL);
instance->count = count;

size = sizeof(instance->items[0]) * instance->count;
memcpy(instance->items, source, size);
```

**Comment by kees** [comment]
treewide patch from Gustavo via Coccinelle: https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=for-next/fam

**Comment by kees** [comment]
Additionally, `Documentation/process/deprecated.rst` should be updated and a test added to `scripts/checkpatch.pl`.

**Comment by kees** [comment]
It would be nice if the compiler had a mode to warn about [0] and [1]-sized arrays.

**Comment by GustavoARSilva** [comment]
testing comments

**Comment by kees** [comment]
Once all the 1-byte arrays are removed from the kernel, we can change UBSan's `-fsanitize=bounds` to `-fsanitze=bounds-strict` for GCC (but not Clang).  See https://github.com/KSPP/linux/issues/25

**Comment by kees** [comment]
> It would be nice if the compiler had a mode to warn about [0] and [1]-sized arrays.

Clang supports `-Wzero-length-array`. I've asked for the [same warning in gcc](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94428).

**Comment by kees** [comment]
> It would be nice if the compiler had a mode to warn about [0] and [1]-sized arrays.

Clang already supports -Wzero-length-array and GCC is open to adding it:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94428

No real traction on a 1-byte array warning, but adding bounds checking should catch those?

**Comment by GustavoARSilva** [comment]
Added treewide patch to testing/fam1 for its further 0-day CI testing:

https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/commit/?h=testing/fam1

**Comment by kees** [comment]
Won't this totally break stuff that is using sizeof() and "- 1" in the wrong places? Or is this just to collect build failure logs?

**Comment by GustavoARSilva** [comment]
> Won't this totally break stuff that is using sizeof() and "- 1" in the wrong places? Or is this just to collect build failure logs?

Yep. The purpose is to collect **non-obvious** build failures in multiple archs. :) I've been documenting the ones I find during my builds (x86_64, allyesconfig). I'm also auditing every instance of this in order to fix the code that makes use of sizeof() and "- 1" --and other variants-- to calculate the total size of the structure.

**Comment by GustavoARSilva** [comment]
> Additionally, `Documentation/process/deprecated.rst` should be updated and a test added to `scripts/checkpatch.pl`.

The documentation patch is ready and waiting for it to be applied:
https://lore.kernel.org/lkml/20200608213711.GA22271@embeddedor/

**Comment by kees** [comment]
All refactoring for fake flexible arrays has been completed. Only the related task of removing flexible arrays in the middle of structures remains.
