### ISSUE TITLE
Replace 1-element array in struct pid

### ISSUE THREAD

**Issue by skitt** [KSPP/linux#231]
`struct pid` uses a 1-element array:

```lang-c
struct pid
{
        refcount_t count;
        unsigned int level;
        spinlock_t lock;
        /* lists of tasks that use this pid */
        struct hlist_head tasks[PIDTYPE_MAX];
        struct hlist_head inodes;
        /* wait queue for pidfd notifications */
        wait_queue_head_t wait_pidfd;
        struct rcu_head rcu;
        struct upid numbers[1];
};
```

I suspect that part of the reason for this is so that a single `struct pid` is a valid level-0 pid, without needing a complementary array allocation; initial allocation of the 0-level cache (`pid_idr_init()` in `kernel/pid.c`) relies on this:

```lang-c
        init_pid_ns.pid_cachep = KMEM_CACHE(pid,
                        SLAB_HWCACHE_ALIGN | SLAB_PANIC | SLAB_ACCOUNT);
```

However the other caches are allocated (`create_pid_cachep` in `kernel/pid_namespace.c`) using a manually setup call to `kmem_cache_create`:

```lang-c
                *pkc = kmem_cache_create(name, len, 0,
                                         SLAB_HWCACHE_ALIGN | SLAB_ACCOUNT, NULL);
```

Presumably using the same pattern (with `SLAB_PANIC` added) would be acceptable for `pid_cachep`.

**Comment by kees** [comment]
https://lore.kernel.org/lkml/20230517225838.never.965-kees@kernel.org/
