### ISSUE TITLE
Detect out of bounds array indexes

### ISSUE THREAD

**Issue by kees** [KSPP/linux#25]
The use of the Undefined Behavior Sanitizer (UBSan)'s "bounds checker" can detect array indexing outside the of known arrays sizes. This feature needs separated from the general UBSan features so it can be enabled independently.

Since builds with libubsan grow the kernel size by almost 5% (for all the debugging), there also needs to be a "trap only" mode for UBSan, which creates a trade-off of having minimal image size impact, but make bounds failures fatal.

**Comment by kees** [comment]
https://lore.kernel.org/lkml/20191121181519.28637-1-keescook@chromium.org/

**Comment by a13xp0p0v** [comment]
Hello @kees !

I've found out that `arm` doesn't have `select ARCH_HAS_UBSAN_SANITIZE_ALL`.
So `UBSAN_SANITIZE_ALL` can't be enabled for `arm`.

Do you know the reason?
Thanks!

**Comment by kees** [comment]
> I've found out that `arm` doesn't have `select ARCH_HAS_UBSAN_SANITIZE_ALL`.
> So `UBSAN_SANITIZE_ALL` can't be enabled for `arm`.
> 
> Do you know the reason?

I assume no one has tried it? I suspect it would likely need gating on ARMv7 CPUs (similar to what the [THREAD_INFO_IN_TASK series](https://lore.kernel.org/lkml/20210907220038.91021-7-keithpac@amazon.com/) does) for reasonably straight-forward testing. I'm sure folks would be open to a tested patch for this! :)

**Comment by kees** [comment]
Commit 277a10850f9f4cb3429faf59293e2c89b1a320be (v5.7)
