### ISSUE TITLE
Fix "invalid application of ‘sizeof’ to incomplete type" error in net/ceph/auth_none.c

### ISSUE THREAD

**Issue by GustavoARSilva** [KSPP/linux#44]
When replacing the zero-length array *reply_buf[0]* with a flexible-array member in *struct ceph_none_authorizer*:

![image](https://user-images.githubusercontent.com/245005/80655739-09cc9380-8a45-11ea-8fbf-a8d02f12adad.png)

the following **error** shows up:

![image](https://user-images.githubusercontent.com/245005/80655954-92e3ca80-8a45-11ea-83ad-fa9f81fc2c9c.png)

This is due to the flexible-array member having [incomplete type](https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html).

See [flexible-array conversions](https://github.com/KSPP/linux/issues/21) issue.

**Comment by kees** [comment]
Perhaps something like this, just to make sure nothing tries to access authorizer_reply_buf...

```
diff --git a/net/ceph/auth_none.c b/net/ceph/auth_none.c
index edb7042479ed..611b8d512c73 100644
--- a/net/ceph/auth_none.c
+++ b/net/ceph/auth_none.c
@@ -94,7 +94,7 @@ static int ceph_auth_none_create_authorizer(
        struct ceph_none_authorizer *au;
        int ret;
 
-       au = kmalloc(sizeof(*au), GFP_NOFS);
+       au = kmalloc(struct_size(au, reply_buf, 0), GFP_NOFS);
        if (!au)
                return -ENOMEM;
 
@@ -109,8 +109,8 @@ static int ceph_auth_none_create_authorizer(
        auth->authorizer = (struct ceph_authorizer *) au;
        auth->authorizer_buf = au->buf;
        auth->authorizer_buf_len = au->buf_len;
-       auth->authorizer_reply_buf = au->reply_buf;
-       auth->authorizer_reply_buf_len = sizeof (au->reply_buf);
+       auth->authorizer_reply_buf = NULL;
+       auth->authorizer_reply_buf_len = 0;
 
        return 0;
 }

```

**Comment by kees** [comment]
I'm curious about net/ceph/messenger.c's process_connect() which passes authorizer_reply_buf with authorizer_len instead of authorizer_reply_buf_len. (authorizer_len seems to be either 0 (safe) or authorizer_buf_len, which would be bad here...

**Comment by GustavoARSilva** [comment]
Ilya just removed the array entirely, so it's never actually used:

https://lore.kernel.org/linux-hardening/CAOi1vP8NARpXVsK2AVOZ4_m58gXMKVQSi_okZVcrLsew1nLizg@mail.gmail.com/
