### ISSUE TITLE
Fix "invalid application of ‘sizeof’ to incomplete type" error in drivers/net/wireless/rndis_wlan.c

### ISSUE THREAD

**Issue by GustavoARSilva** [KSPP/linux#45]
When replacing the zero-length array *auth_encr_pair[0]* with a flexible-array member in *struct ndis_80211_capability*:

![image](https://user-images.githubusercontent.com/245005/80656307-7a27e480-8a46-11ea-9ca5-ec0fd5ce514d.png)

the following **error** shows up:

![image](https://user-images.githubusercontent.com/245005/80656476-ec002e00-8a46-11ea-8c99-8f914e0cb2a1.png)

This is due to the flexible-array member having [incomplete type](https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html).

See [flexible-array conversions](https://github.com/KSPP/linux/issues/21) issue.

**Comment by GustavoARSilva** [comment]
https://lore.kernel.org/lkml/20200505235205.GA18539@embeddedor/

**Comment by kees** [comment]
It looks like nothing is actually using the auth_encr_pair bytes, so I'd agree with your patch! :)

**Comment by GustavoARSilva** [comment]
Patch applied and waiting to be added to mainline: https://lore.kernel.org/lkml/20200512085336.B8DE4C433CB@smtp.codeaurora.org/

**Comment by GustavoARSilva** [comment]
The patch is already upstream:
[rndis_wlan: Remove logically dead code](https://git.kernel.org/linus/f2cd32a443da694ac4e28fbf4ac6f9d5cc63a539)
