### ISSUE TITLE
Replace UAPI zero-length arrays with flexible-array members

### ISSUE THREAD

**Issue by GustavoARSilva** [KSPP/linux#80]
See [Replace zero-length arrays with flexible-array members](https://github.com/KSPP/linux/issues/78)

This has been reverted for now[1].

[1] commit 1e6e9d0f4859 ("uapi: revert flexible-array conversions")

There are currently 84 files containing zero-length arrays in uapi/

**Comment by GustavoARSilva** [comment]
Current patch being tested (on top of 5.18-rc1):

https://git.kernel.org/pub/scm/linux/kernel/git/gustavoars/linux.git/log/?h=for-next/kspp-fam0-uapi

**Comment by kees** [comment]
See commit 94dfc73e7cf4a31da66b8843f0b9283ddd6b8381.
