### ISSUE TITLE
Add FORTIFY_SOURCE to strscpy()

### ISSUE THREAD

**Issue by kees** [KSPP/linux#96]
While `strscpy()` is safe for runtime checks on the destination size, it does not actually perform any compile-time assisted buffer size validation (neither at compile time nor at runtime). It'd be nice to grow those checks to avoid problems that could be detected at compile time (or get set up to be detected at runtime).

For example, this would not be detected at compile time nor runtime:

```
char dest[8];

strscpy(dest, src, 16);
```

And to likely gain further checking, `strscpy_pad()` needs to be made a static inline so the buffer sizes will become "visible" to the compiler when passing the arguments into `strscpy()`.

**Comment by eiffel-fl** [comment]
Hi.


First, I do hope you are fine and the same for your relatives.

I would like to try to fix this issue.
If I am correct, the goal is to write a `__FORTIFY_INLINE`'d version of `strscpy` like what exists for [strcpy](https://elixir.bootlin.com/linux/latest/source/include/linux/string.h#L483)?


Best regards.

**Comment by kees** [comment]
> First, I do hope you are fine and the same for your relatives.

Thanks; same for you!

> I would like to try to fix this issue.
> If I am correct, the goal is to write a `__FORTIFY_INLINE`'d version of `strscpy` like what exists for [strcpy](https://elixir.bootlin.com/linux/latest/source/include/linux/string.h#L483)?

Correct. It likely needs some special handling/renaming, as `strscpy()` is already the target for the existing `FORTIFY` functions.

Adding test cases would be very nice as well, likely in LKDTM (`drivers/misc/lkdtm/`) somewhere.

**Comment by eiffel-fl** [comment]
> Thanks; same for you!

You are welcome!
 
> Correct. It likely needs some special handling/renaming, as `strscpy()` is already the target for the existing `FORTIFY` functions.

I think I wrote something that fortifies `strscpy()`.
But I have some question about it, for example do I need to set copy size to the min between `q` length and the function `size` argument?
Moreover, adding this fortified version shows bugs into kernel source, do I need to correct them with the same patch? 
Maybe it is better to discuss all this on the KSPP project mailing list?

> Adding test cases would be very nice as well, likely in LKDTM (`drivers/misc/lkdtm/`) somewhere.

Do you have documentation about LKDTM? I do not really understand how does it work?
Since fortified version are mainly about throwing errors at compile time is this thing needed?

**Comment by kees** [comment]
> Do you have documentation about LKDTM? I do not really understand how does it work...

Sure! See here, which goes in to generally more detail than needed: https://www.kernel.org/doc/html/latest/fault-injection/provoke-crashes.html

After building with `CONFIG_LKDTM=y`, with debugfs mounted at `/sys/kernel/debug` (the default location), you use it:

- To see the available triggers:

  `cat /sys/kernel/debug/provoke_crash/DIRECT`

- To trigger a test:

  `echo $name >/sys/kernel/debug/provoke_crash/DIRECT`

**Comment by eiffel-fl** [comment]
Thank you for the documentation!
I will try to use LKDTM to test the runtime panic.
Indeed, I am not really happy with my actual modifications because it test it too few...

**Comment by kees** [comment]
Landed upstream in commit 33e56a59e64dfb68778e5da0be13f0c47dc5d445.
